[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
name = "install"
cmd = "bun install"

[phases.build]
name = "build"
cmd = "bun run build:web"

[start]
cmd = "cd apps/web && bun run start"
